- tap:
    - homebrew/cask-fonts

- brew:
    - automake
    - atom
    - bat
    - cmake
    - cyberduck
    - cowsay
    - coreutils
    - docker
    - emacs
    - exercism
    - fish
    - fortune
    - gh
    - git
    - github
    - git-flow
    - graphviz
    - hugo
    - iterm2
    - libreoffice
    - node
    - nvm
    - openssl
    - pyenv
    - python
    - python@3.8
    - python@3.9
    - pipenv
    - postgresql
    - rust
    - slack
    - sass/sass/sass
    - sassc
    - telegram
    - xxh
    - visual-studio-code
    - vlc
    - zoom

- cask:
    - kitty
    - font-hack-nerd-font
