- tap:
    - homebrew/cask-fonts

- brew:
    - automake
    - bat
    - cmake
    - cowsay
    - coreutils
    - emacs
    - exercism
    - fish
    - firefox
    - fortune
    - gh
    - git
    - git-flow
    - graphviz
    - hugo
    - node
    - nvm
    - openssl
    - pyenv
    - python
    - python@3.8
    - python@3.9
    - pipenv
    - postgresql
    - rust
    - sass/sass/sass
    - sassc
    - thunderbird
    - xxh

- cask:
    - kitty
    - font-hack-nerd-font
