- create:
    ~/Coding:
    ~/Coding/Alilaguna:
    ~/Coding/Elan42:
    ~/Coding/Personale:

- link:
    ~/.gitattributes:
    ~/.gitconfig:
    ~/.gitignore_global:
    ~/.git-hooks:
    ~/.gitmessage:
    ~/.git-identities:
    ~/.config/gh/config.yml: config/gh/config.yml

- shell:
    - [chmod +x ~/.git-hooks/*]
