- link:
          ~/.ipython/profile_default/ipython_config.py: ipython/profile_default/ipython_config.py
          ~/.ipython/profile_default/ipython_kernel_config.py: ipython/profile_default/ipython_kernel_config.py
          ~/.ipython/profile_default/startup: ipython/profile_default/startup
