- create:
    ~/Coding:
    ~/.gostuff:
    ~/.ipython:
    ~/.jupyter:
    ~/.gem:
    ~/.ploty:
    ~/.poetry:
    ~/.rustup:

- link:
    ~/.editorconfig: .editorconfig
    ~/.flake8:
    ~/.hushlogin:
