- create:
    ~/Coding:
    ~/.gostuff:
    ~/.ipython:
    ~/.jupyter:
    ~/.gem:
    ~/.ploty:
    ~/.poetry:
    ~/.rustup:

- link:
    ~/.editorconfig:
    ~/.alacritty.yml:
    ~/AppData/Roaming/alacritty/alacritty.yml: alacritty.yml
    ~/.servergrimoire:
