- create:
          ~/Coding:
          ~/.gostuff:
          ~/.ipython:
          ~/.jupyter:
          ~/.gem:
          ~/.ploty:
          ~/.poetry:
          ~/.rustup:

- link:
          ~/.editorconfig:
          ~/.alacritty.yml:
          ~/.servergrimoire:
