- create:
          ~/.oh-my-zsh-custom/themes:
          ~/.oh-my-zsh-custom/plugins:
          ~/.oh-my-zsh-custom/plugins/zsh-syntax-highlighting:

- link:
          ~/.zprofile:
          ~/.zshrc:
          ~/.oh-my-zsh: .oh-my-zsh
          ~/.oh-my-zsh-custom/themes/spaceship.zsh-theme: .spaceship/spaceship.zsh-theme
          ~/.oh-my-zsh-custom/plugins/zsh-autosuggestions: .zsh-autosuggestions
          ~/.oh-my-zsh-custom/plugins/zsh-syntax-highlighting: .zsh-syntax-highlighting
          ~/.oh-my-zsh-custom/plugins/bofh: .bofh
