brew install bat
brew install cowsay
brew install dart-lang/dart/dart
brew install elixir
brew install emacs
brew install exercism
brew install fish
brew install fortune
brew install gh
brew install git-flow
brew install go
brew install graphviz
brew install heroku/brew/heroku
brew install hugo
brew install pipenv
brew install postgresql
brew install pyenv
brew install redis
brew install rust
brew install sass/sass/sass
brew install sassc
brew install sphinx-doc
brew install starship
brew install zsh
