choco install openssh
choco install makefile
choco install googlechrome
choco install vlc
choco install git
choco install 7zip
choco install inkscape
choco install vscode
choco install jetbrainstoolbox
choco install thunderbird
choco install libreoffice-fresh
choco install filezilla
choco install firacode
choco install firefox
choco install postgresql
choco install alacritty
choco install python
choco install rust
choco install elixir
choco install golang
choco install postgresql
choco install pgadmin4
