- defaults:
          link:
                  create: true
                  relink: true
                  force: true

- create:
          ~/Coding:
          ~/.gostuff:

- link:
          ~/.editorconfig:
          ~/.gitconfig:
          ~/.gitignore_global:
          ~/.irbrc:
          ~/.Xresources:
          ~/.zshrc:
          ~/.ssh/config: ssh/config
          ~/.config/darktable: config/darktable
          ~/.config/neofetch: config/neofetch
          ~/.config/twtxt: config/twtxt
          ~/script:
          ~/.emacs.d:

- shell:
          - [git submodule update --init --recursive, Installing submodules]
          - [chmod +x ~/script/*]
