- defaults:
          link:
                  create: true
                  relink: true
                  force: true

- link:
          ~/script:
          ~/.sslverify:
          ~/.djangocheck:
          ~/.dnschecker:

- shell:
          - [chmod +x ~/script/*]

- clean: ["~"]
