- defaults:
          link:
                  create: true
                  relink: true
                  force: true

- link:
          ~/script:

- shell:
          - [git submodule sync --recursive, Synchronize the URLs of submodules]
          - [git submodule update --init --recursive, Update the submodules]
          - [chmod +x ~/script/*]
          - [
                    '[[ "$(uname -a)" = *[M,m]icrosoft* ]] && sudo cp --remove-destination "linux/wsl/wsl.conf" /etc/wsl.conf',
                    Force re-copy wsl configs,
            ]

- clean: ["~"]
