- defaults:
    link:
      create: true
      relink: true
      force: true

- link:
    ~/script:

- shell:
    - [git submodule update --init --recursive, Installing submodules]
    - [chmod +x ~/script/*]

- clean: ["~"]
