- defaults:
          link:
                  create: true
                  relink: true
                  force: true

- link:
          ~/.script:
          ~/.servergrimoire:

- shell:
          - [chmod +x ~/script/*]

- clean: ["~"]
