- defaults:
          link:
                  create: true
                  relink: true
                  force: true

- link:
          ~/script:

- shell:
          - [git submodule sync --recursive, Synchronize the URLs of submodules]
          - [git submodule update --init --recursive, Update the submodules]
          - [chmod +x ~/script/*]

- clean: ["~"]
