- defaults:
          link:
                  create: true
                  relink: true
                  force: true

- link:
          ~/script:

- shell:
          - [chmod +x ~/script/*]

- clean: ["~"]
