#!/usr/bin/env python

import json
import requests
from tabulate import tabulate

url = " http://apps.unive.it/sitows/index/personebiblioteche"

response = requests.get(url)
data = response.json()
end_message = []
for key in list(data.keys()):
    end_message.append((key, f"{data[key]['persone']}/{data[key]['max']}"))

print(tabulate(end_message, ["Biblioteca", "Posti"], tablefmt="pipe"))
