#!/usr/bin/env python

import json
import urllib.error
import urllib.request
from tabulate import tabulate

url = "http://static.unive.it/sitows/index/personebiblioteche"

response = urllib.request.urlopen(url)
data = json.loads(response.read())
end_message = []
for key in list(data.keys()):
    end_message.append((key, f"{data[key]['persone']}/{data[key]['max']}"))

print(tabulate(end_message, ["Biblioteca", "Posti"], tablefmt="pipe"))
