#!/usr/bin/env python
import logging
import os
import sys

import dns.resolver
from tabulate import tabulate

log = logging.getLogger("DNSLookup")


def dns_lookup(domain):
  array_input = [(domain, 'A'), (domain, 'MX'), ('mail.' + domain, 'A'), (domain, 'NS'), (domain, 'TXT')]
  output = [[domain, ""]]

  for query, label in array_input:
    try:
      for rdata in dns.resolver.resolve(query, label):
        output.append([label, str(rdata)])
    except:
      log.info(f"Not found {label} for {domain}")
  return output


if __name__ == "__main__":
  if len(sys.argv) > 1:
    for e in sys.argv[1:]:
      print(tabulate(dns_lookup(e), [e,""], tablefmt="pipe"))
  else:
    f = open(os.path.expanduser("~/.dnschecker"), "r", encoding="utf-8")
    end_message = []
    for host in f.readlines():
      host = host.strip()
      print(tabulate(dns_lookup(host), [host,""], tablefmt="pipe"))
      print()
