#!/usr/bin/env python

import requests


def nekoGET(endpoint):
    r = requests.get("https://neko-love.xyz/api/v1/" + endpoint)
    if r.status_code != 200:
        return("An error has occurred")
    else:
        return(r.json()["url"])


print(nekoGET("neko"))
