#!/usr/bin/env python3

import random

foo = [
    "¯\_(ツ)_/¯",
    "(｀∀´)Ψ",
    "(ó﹏ò｡)",
    "( ͡° ͜ʖ ͡°)",
    "(•ω•)",
    "(°,,,°)",
    "(;,,;)",
    "(~#~)",
    "(͠≖ ͜ʖ͠≖)",
    "( ಠ ͜ʖರೃ)",
    "ლ(´ڡ`ლ)",
]
print(random.choice(foo).capitalize() + " ")
