#!/usr/bin/env python

import sys
import shutil
import re
import os
from os import listdir
from os.path import isfile, join

if len(sys.argv) > 1:
    path = sys.argv[1]
else:
    path = "."

onlyfiles = [f for f in listdir(path) if isfile(join(path, f))]

for e in onlyfiles:
    print(e)
    if "COPIADIP" in e:
        p = re.compile("COPIADIP-(.*)-(.*)-000620.pdf")
        result = p.search(e)
        print(f" {result.group(1)} {result.group(2)}")
        os.rename(e, f"{result.group(2)}-{result.group(1)}-alilaguna.pdf")
